use eframe::egui::Key as EguiKey;
use rdev::Key as RdevKey;

pub struct Convert;  // for anyone tryna implement custom keybinds (I can't be arsed)

impl Convert {
    pub fn egui_to_rdev_key(key: EguiKey) -> Option<RdevKey> {
        match key {
            EguiKey::ArrowUp => Some(RdevKey::UpArrow),
            EguiKey::ArrowDown => Some(RdevKey::DownArrow),
            EguiKey::ArrowLeft => Some(RdevKey::LeftArrow),
            EguiKey::ArrowRight => Some(RdevKey::RightArrow),
            EguiKey::Escape => Some(RdevKey::Escape),
            EguiKey::Enter => Some(RdevKey::Return),
            EguiKey::Tab => Some(RdevKey::Tab),
            EguiKey::Backspace => Some(RdevKey::Backspace),
            EguiKey::Space => Some(RdevKey::Space),
            EguiKey::Insert => Some(RdevKey::Insert),
            EguiKey::Delete => Some(RdevKey::Delete),
            EguiKey::Home => Some(RdevKey::Home),
            EguiKey::End => Some(RdevKey::End),
            EguiKey::PageUp => Some(RdevKey::PageUp),
            EguiKey::PageDown => Some(RdevKey::PageDown),
            EguiKey::Quote => Some(RdevKey::Quote),
            EguiKey::Num0 => Some(RdevKey::Num0),
            EguiKey::Num1 => Some(RdevKey::Num1),
            EguiKey::Num2 => Some(RdevKey::Num2),
            EguiKey::Num3 => Some(RdevKey::Num3),
            EguiKey::Num4 => Some(RdevKey::Num4),
            EguiKey::Num5 => Some(RdevKey::Num5),
            EguiKey::Num6 => Some(RdevKey::Num6),
            EguiKey::Num7 => Some(RdevKey::Num7),
            EguiKey::Num8 => Some(RdevKey::Num8),
            EguiKey::Num9 => Some(RdevKey::Num9),
            EguiKey::A => Some(RdevKey::KeyA),
            EguiKey::B => Some(RdevKey::KeyB),
            EguiKey::C => Some(RdevKey::KeyC),
            EguiKey::D => Some(RdevKey::KeyD),
            EguiKey::E => Some(RdevKey::KeyE),
            EguiKey::F => Some(RdevKey::KeyF),
            EguiKey::G => Some(RdevKey::KeyG),
            EguiKey::H => Some(RdevKey::KeyH),
            EguiKey::I => Some(RdevKey::KeyI),
            EguiKey::J => Some(RdevKey::KeyJ),
            EguiKey::K => Some(RdevKey::KeyK),
            EguiKey::L => Some(RdevKey::KeyL),
            EguiKey::M => Some(RdevKey::KeyM),
            EguiKey::N => Some(RdevKey::KeyN),
            EguiKey::O => Some(RdevKey::KeyO),
            EguiKey::P => Some(RdevKey::KeyP),
            EguiKey::Q => Some(RdevKey::KeyQ),
            EguiKey::R => Some(RdevKey::KeyR),
            EguiKey::S => Some(RdevKey::KeyS),
            EguiKey::T => Some(RdevKey::KeyT),
            EguiKey::U => Some(RdevKey::KeyU),
            EguiKey::V => Some(RdevKey::KeyV),
            EguiKey::W => Some(RdevKey::KeyW),
            EguiKey::X => Some(RdevKey::KeyX),
            EguiKey::Y => Some(RdevKey::KeyY),
            EguiKey::Z => Some(RdevKey::KeyZ),
            EguiKey::F1 => Some(RdevKey::F1),
            EguiKey::F2 => Some(RdevKey::F2),
            EguiKey::F3 => Some(RdevKey::F3),
            EguiKey::F4 => Some(RdevKey::F4),
            EguiKey::F5 => Some(RdevKey::F5),
            EguiKey::F6 => Some(RdevKey::F6),
            EguiKey::F7 => Some(RdevKey::F7),
            EguiKey::F8 => Some(RdevKey::F8),
            EguiKey::F9 => Some(RdevKey::F9),
            EguiKey::F10 => Some(RdevKey::F10),
            EguiKey::F11 => Some(RdevKey::F11),
            EguiKey::F12 => Some(RdevKey::F12),
            _ => None,
        }
    }
}
